VMO-6575 Adjust button spacing
FLOIP/flow-builder pull request #321
Opened 2022-08-16 09:03 UTC by object-required

<img width="681" alt="image" src="https://user-images.githubusercontent.com/3971957/184841274-9b90ca39-f3ce-41d4-8fb7-97d531be2d32.png">

2022-08-16 17:16 UTC, seifertk commented
Should the `Default` button on the SetContactProperty be taking the full width of the box?
![image](https://user-images.githubusercontent.com/894677/184939605-a8357599-44c7-4e59-bce9-8187c5a508a5.png)

2022-08-16 18:30 UTC, safydy-r requested changes
- [x] make sure all single exit block follow the AC (like Kyle mentioned in his screenshot), in current screenshot you still have setContactProp not following it.

2022-08-17 11:40 UTC, bulatgab approved these changes

2022-08-17 15:22 UTC, safydy-r approved these changes
Thanks @object-required

2022-08-18 18:57 UTC, merged