CORE-538, CORE-545 Block connections
FLOIP/flow-builder pull request #464
Opened 2023-05-29 18:53 UTC by object-required

2023-05-29 22:07 UTC, safydy-r approved these changes
happy this worked & was easier than we thought :D

2023-05-30 11:16 UTC, bulatgab commented
@object-required 
I don't understand how it works 😅 Could you please explain?

2023-05-30 11:16 UTC, bulatgab commented
I've noticed that if we remove the connection by clicking on the exit, it can't be undone. Could you please check?
<img width="268" alt="Screenshot 2023-05-30 at 1 14 34 PM" src="https://github.com/FLOIP/flow-builder/assets/18130716/9babd966-1537-4463-9f9e-45fbf7b2e177">

2023-05-30 11:19 UTC, bulatgab requested changes
- [ ] please leave a comment on how/why deactivateAllConnections removes the connection
- [ ] fix the 'undo remove connection'

2023-05-30 12:29 UTC, object-required commented on src/store/undoRedo/index.ts
> +
@bulatgab creating and deleting block connections right away fell under the "we changed the same thing" category; I created a list of overrides with store paths that should always produce a new snapshot.

2023-05-30 14:39 UTC, merged