CORE-549, CORE-634 Flow resources
FLOIP/flow-builder pull request #492
Opened 2023-06-20 12:17 UTC by object-required

2023-06-20 13:55 UTC, safydy-r commented on cypress/e2e/flow-builder/undo-redo/block-resources.cy.js
> +      label: 'Undo-redo test',
maybe "undo-redo block resources"

2023-06-20 14:00 UTC, safydy-r commented on cypress/support/commands.ts
> +Cypress.Commands.add('setBlockText', (language: string, channel: string, value: string) => {
I'd suggest we rename it to "setBlockTextResource"

2023-06-20 14:02 UTC, safydy-r requested changes
in general it's good, left minor change requests. Let me know if you have a question

2023-06-20 23:35 UTC, safydy-r approved these changes
LGTM

2023-06-20 23:59 UTC, merged

2023-06-21 09:22 UTC, bulatgab commented on cypress/support/commands.ts
> +    return cy.wrap(editor)
👍

2023-06-21 09:27 UTC, bulatgab commented on src/components/interaction-designer/resource-editors/ResourceVariantTextEditor.vue
> +          :cypress-data-attribute="`resource--${mode}`.toLowerCase()"
When do we use `cypress-data-attribute` vs `data-cy`?

2023-06-21 09:29 UTC, bulatgab commented on cypress/e2e/flow-builder/undo-redo/block-resources.cy.js
> +})
👍