feature/CORE-605/create-contact-property-from-flow-builder
FLOIP/flow-builder pull request #508
Opened 2023-07-18 21:30 UTC by bulatgab

2023-07-18 21:34 UTC, bulatgab commented on src/builder.config.json
Not sure why it is shown as new, the idea was to move it from root folder to `src`

2023-07-18 21:34 UTC, bulatgab commented on src/app.config.json
Not sure why it is shown as new, the idea was to move it from root folder to `src`

2023-07-18 21:35 UTC, bulatgab commented on dist/types/builder.config.json
there it is - 1

2023-07-18 21:35 UTC, bulatgab commented on dist/types/app.config.json
there it is - 2

2023-07-18 23:10 UTC, object-required approved these changes

2023-07-19 21:55 UTC, safydy commented on src/app.config.json
thanks for the solution, let's pair tmr to fix the CI build ;)

2023-07-19 21:55 UTC, safydy requested changes
Let's pair to fix the CI build tmr

2023-07-25 00:12 UTC, bulatgab commented on src/components/interaction-designer/block-editors/choices/SelectOneResponseBlockContactPropertyEditor.vue
these changes were not necessary, but I kept them

2023-07-26 16:08 UTC, merged