VMO-3679  Builder should only output resource value with single SupportedContentType
FLOIP/flow-builder pull request #79
Opened 2021-05-06 15:24 UTC by poojahpatil90

Note to reviewers: I could not test the storybook changes on my machine, some issue with rendering the storybook view. I will reach out to @safydy-r once he is back to test it on his machine.

2021-06-04 00:00 UTC, safydy-r requested changes
@poojahpatil90 , it's almost there. I left minor comment above to remove one TODO. Apart from that, as `master` no longer has TS issue, could you pls update from master and see if your current TS error will be gone (normally it should be as Jacob has fixed it) ?
```
ERROR in /Users/rs/Documents/Voto/floip/flow-builder/src/store/flow/utils/importHelpers.ts(2,3):
2:3 Module '"@floip/flow-runner"' has no exported member 'IResourceDefinition'.
    1 | import {
  > 2 |   IResourceDefinition,
      |   ^
    3 |   IContext,
    4 |   IBlock,
    5 | } from '@floip/flow-runner'
ERROR in /Users/rs/Documents/Voto/floip/flow-builder/src/store/flow/utils/importHelpers.ts(16,44):
16:44 Parameter 'value' implicitly has an 'any' type.
    14 | export const updateResourcesForLanguageMatch = function (resources: IResourceDefinition[], oldId: string, newId: string): IResourceDefinition[] {
    15 |   return resources.map((resource) => {
  > 16 |     resource.values = resource.values.map((value) => {
       |                                            ^
    17 |       if (value.languageId === oldId) {
    18 |         value.languageId = newId
    19 |       }
Version: typescript 4.2.4
Time: 9131ms
```

Let me know once you have confirmation it's clean, so I'd be happy to approve the PR

2021-06-04 00:09 UTC, safydy-r commented on stories/story-utils/storeSetup.ts
>      // TODO: find better way to do this once the resource editor is fully implemented, the goal is to set resources' value correctly. The implementation below is just an
I'm glad we have this fixed. It's been a while we lug this around sprints :p

2021-06-07 17:48 UTC, poojahpatil90 commented on stories/story-utils/storeSetup.ts
>      // TODO: find better way to do this once the resource editor is fully implemented, the goal is to set resources' value correctly. The implementation below is just an
Done!

2021-06-07 17:49 UTC, poojahpatil90 commented
> @poojahpatil90 , it's almost there. I left minor comment above to remove one TODO. Apart from that, as `master` no longer has TS issue, could you pls update from master and see if your current TS error will be gone (normally it should be as Jacob has fixed it) ?
> 
> ```
> ERROR in /Users/rs/Documents/Voto/floip/flow-builder/src/store/flow/utils/importHelpers.ts(2,3):
> 2:3 Module '"@floip/flow-runner"' has no exported member 'IResourceDefinition'.
>     1 | import {
>   > 2 |   IResourceDefinition,
>       |   ^
>     3 |   IContext,
>     4 |   IBlock,
>     5 | } from '@floip/flow-runner'
> ERROR in /Users/rs/Documents/Voto/floip/flow-builder/src/store/flow/utils/importHelpers.ts(16,44):
> 16:44 Parameter 'value' implicitly has an 'any' type.
>     14 | export const updateResourcesForLanguageMatch = function (resources: IResourceDefinition[], oldId: string, newId: string): IResourceDefinition[] {
>     15 |   return resources.map((resource) => {
>   > 16 |     resource.values = resource.values.map((value) => {
>        |                                            ^
>     17 |       if (value.languageId === oldId) {
>     18 |         value.languageId = newId
>     19 |       }
> Version: typescript 4.2.4
> Time: 9131ms
> ```
> 
> Let me know once you have confirmation it's clean, so I'd be happy to approve the PR

@safydy-r  Merged master to this branch and attached a screenshot for your reference.

<img width="1536" alt="Screen Shot 2021-06-07 at 10 28 39 AM" src="https://user-images.githubusercontent.com/23651142/121065768-fa5a6680-c77d-11eb-942d-fff0d89c5c1a.png">

2021-06-14 15:04 UTC, safydy-r approved these changes
@poojahpatil90 , I'm approving it. Good job

2021-06-29 14:38 UTC, merged